
--USER
INSERT INTO USER (ID, USERNAME,FIRSTNAME,LASTNAME,PASSWORD,EMAIL) VALUES (1, 'ANTONIOTEST', 'Antonio', 'Redondo', 'PASSWORDTEST','ANTONIO@GMAIL.COM');
INSERT INTO USER (ID, USERNAME,FIRSTNAME,LASTNAME,PASSWORD,EMAIL) VALUES (2, 'HAROONTEST', 'Haroon', 'Subair', 'PASSWORDTESTHAROON','HAROON@GMAIL.COM');