
--USER
INSERT INTO USER (ID, USERNAME,FIRSTNAME,LASTNAME,PASSWORD,EMAIL) VALUES (1, 'ANTONIOTEST', 'Antonio', 'Redondo', 'PASSWORDTEST','ANTONIO@GMAIL.COM');
INSERT INTO USER (ID, USERNAME,FIRSTNAME,LASTNAME,PASSWORD,EMAIL) VALUES (2, 'HAROONTEST', 'Haroon', 'Subair', 'PASSWORDTESTHAROON','HAROON@GMAIL.COM');


--PROPERTY
INSERT INTO PROPERTY (PROPERTY_ID, NAME,ADDRESS,CITY,IMAGE) VALUES (1, 'INDEX TOWER', 'DIFC', 'Dubai', 'PropertyImage');

--TASK
INSERT INTO TASK (TASK_ID, DATE_FROM,DATE_TO,REMARKS,IMAGE) VALUES (1, to_date('20170604','YYYYMMDD'), to_date('20170704','YYYYMMDD'), 'Task Remarks', 'TaskImage');


--EMPLOYEE
INSERT INTO EMPLOYEE (ID, NAME,EMAIL,TELEPHONE,ADDRESS,REMARKS,CITY,AGE,IMAGE,PROPERTY_ID,TASK_ID) VALUES (1, 'Jesus Redondo', 'jesus@gmail.com', '971501844741', 'JBR Sadaf8','Jesus remarks', 'Malaga', 33, 'image', 1,1);
--EMPLOYEE
INSERT INTO EMPLOYEE (ID, NAME,EMAIL,TELEPHONE,ADDRESS,REMARKS,CITY,AGE,IMAGE,PROPERTY_ID,TASK_ID) VALUES (2, 'Jessica Vasco', 'Jessica@gmail.com', '971451777139', 'JLT Palladium Tower','Jessica remarks', 'London', 22, 'image', 1,1);
--EMPLOYEE
INSERT INTO EMPLOYEE (ID, NAME,EMAIL,TELEPHONE,ADDRESS,REMARKS,CITY,AGE,IMAGE,PROPERTY_ID,TASK_ID) VALUES (3, 'Barrett Milner', 'Barrett@gmail.com', '971333587231', 'Deira Street','Barrett remarks', 'Paris', 51, 'image', 1,1);
--EMPLOYEE
INSERT INTO EMPLOYEE (ID, NAME,EMAIL,TELEPHONE,ADDRESS,REMARKS,CITY,AGE,IMAGE,PROPERTY_ID,TASK_ID) VALUES (4, 'Brody Smith', 'Brody@gmail.com', '971551769326', 'Dubai Creek','Brody remarks', 'Manchester', 17, 'image', 1,1);





