CREATE TABLE USER
(
	ID NUMBER(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR2(50) NOT NULL,
	FIRSTNAME VARCHAR2(50) NOT NULL,
	LASTNAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NULL,
);