CREATE TABLE USER
(
	ID NUMBER(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR2(50) NOT NULL,
	FIRSTNAME VARCHAR2(50) NOT NULL,
	LASTNAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NULL
);

CREATE TABLE PROPERTY
(
	PROPERTY_ID NUMBER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(50) NOT NULL,
	CITY VARCHAR2(50) NOT NULL,
	IMAGE VARCHAR2(50) NULL
);

CREATE TABLE TASK
(
	TASK_ID NUMBER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DATE_FROM DATE NULL,
	DATE_TO DATE NULL,
	REMARKS VARCHAR2(50) NOT NULL,
	IMAGE VARCHAR2(50) NULL,
	NAME VARCHAR2(50) NOT NULL

);

CREATE TABLE EMPLOYEE
(
	ID NUMBER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL,
	TELEPHONE VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(50) NULL,
	REMARKS VARCHAR2(50) NULL,
	CITY VARCHAR2(50) NULL,
	AGE NUMBER(3)NOT NULL,
	IMAGE VARCHAR2(50) NULL,
	PROPERTY_ID NUMBER(10)NOT NULL,
	TASK_ID NUMBER(10)NOT NULL,
	CONSTRAINT fk_property FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
	CONSTRAINT fk_task FOREIGN KEY (TASK_ID) REFERENCES TASK(TASK_ID)
);




